PR-2572 Removing ignore_keys
Causes this error on deploy:
```
Error: Unsupported block type

  on common.tf line 11, in provider "aws":
  11:   ignore_tags {

Blocks of type "ignore_tags" are not expected here. Did you mean to define
argument "ignore_tags"? If so, use the equals sign to assign it a value.
```